package:
  name: qutil
  version: 3.3.0

build:
  number: 0
  noarch: true
  script:
    - QPATH=$PREFIX/q/lib DEST=$QPATH/"$PKG_NAME"-"$PKG_VERSION"
    - mkdir -p $DEST $PREFIX/etc/conda/{de,}activate.d
    - cp $SRC_DIR/q_q.sample $PREFIX/q/q.q
    - cp $SRC_DIR/lib/bootstrap.q $QPATH
    - cp $SRC_DIR/lib/{config_parse,init,opts}.q $DEST
    - for i in {de,}activate; do cp "$RECIPE_DIR"/"$i".sh "$PREFIX"/etc/conda/"$i".d/"$PKG_NAME"_"$i".sh; done  # TODO: decom *activate.sh; use `conda env config vars set`

source:
  - git_url: https://github.com/danielkrizian/qutil.git
    git_rev: {{ PKG_VERSION }}
    git_depth: 1
  - path: ./

test:
  requires:
    - q
    - qspec
  source_files:
    - test
    - test_require
  commands:
    - test $QINIT = $CONDA_PREFIX/q/q.q
    - test -f $QINIT
    - test -f $QPATH/bootstrap.q
    - echo ".utl.require\"qutil\";.utl.configParsing;.utl.addArg;exit 0" > test.q && q test.q -q
    - echo ".utl.require\"qutil/config_parse.q\"" > init.q && spec.q init.q test
    - spec.q test_require/test_require.q

about:
  home: https://github.com/nugend/qutil
  license: MIT
  license_file: LICENSE
  summary: Q utilities by Dan Nugent, including package loading with version support

extra:
  author: Daniel Nugent
  author_email: nugend@gmail.com
