# {% set version = "0.0.1" %}

package:
  name: {{ PKGNAME }}
  version: {{ VER }}

source:
  - path: ../{{ PKG_NAME }}.q

build:
  number: auto
  noarch: true
  script_env:
    - PKGNAME
    - VER
  script:
    - DEST=$QPATH/"$PKG_NAME"-"$PKG_VERSION"
    - mkdir -p $DEST
    - cp $SRC_DIR/"$PKG_NAME".q $DEST

requirements:
  build:
    - qutil
  run:
    - qutil

test:
  requires:
    - q
    - qspec
    - ut
  files:
    - ../test/{{ PKG_NAME }}.q
    - ../test/{{ PKG_NAME }}/*
  commands:
    - test -d {{ PKG_NAME }} && mkdir test && mv {{ PKG_NAME }} test/
    - spec.q --fail-hard $QPATH/{{ PKG_NAME }}-{{ PKG_VERSION }}/{{ PKG_NAME }}.q {{ PKG_NAME }}.q

about:
  home: https://github.com/arqive/qlib
  license: MIT
  license_file: ../LICENSE
  summary: standard libraries for q/kdb+

extra:
  author: Daniel Krizian
  author_email: daniel.krizian@gmail.com
