package:
  name: qffi
  version: 0.11.0

source:
  - url: https://github.com/KxSystems/ffi/releases/download/v0.11.0/ffi_linux-v0.11.0.tar.gz
    folder: src

requirements:
  build:
    - q
    - qutil
  run:
    - libffi>=3.1
    - q
    - qutil

build:
  script:
    - DEST=$QPATH/"$PKG_NAME"-"$PKG_VERSION"
    - mkdir -p $DEST
    - cp src/ffi.q $DEST
    - cp src/ffi.q "${QHOME}"/ 
    - echo "\\l ffi.q" > init.q && cp init.q $DEST
    - cp -r src/l64 "${QHOME}"/ #[linux and x86_64]
    - cp -r src/l32 "${QHOME}"/ #[not x86_64]

test:
  requires:
    - q
  source_files:
    - src/*ffi.q
  commands:
    - cp src/ffi.q "${QHOME}"/  # just to satisfy src/test_ffi.q:1: \l ffi.q
    - numactl --physcpubind=0 q src/test_ffi.q -q #[linux64] 
    - echo ".utl.require\"qffi\";.ffi;exit 0" | numactl --physcpubind=0 q -q

about:
  home: https://github.com/kxsystems/ffi
  license: Apache-2.0
  license_file: src/LICENSE.ffi
  summary: Foreign function interface for kdb+ http://code.kx.com/q/interfaces/ffi/
